# .gitlab-ci-check-docker-build.yml
#
# This gitlab-ci template builds a Docker image and publishes it
# on Docker Hub or Mender Registry
#
# Requires DOCKER_REPOSITORY variable to be set in the calling Pipeline.
# Add it to the project in hand through Gitlab's include functionality
# variables:
#   DOCKER_REPOSITORY: <Image FQN, i.e mendersoftware/reponame>
# include:
#   - project: 'Northern.tech/Mender/mendertesting'
#     file: '.gitlab-ci-check-docker-build.yml'
#
# It assumes a Dockerfile in the root of the repository. A different
# directory can optionally be specified using DOCKER_DIR variable:
# variables:
#   DOCKER_DIR: <relative path, i.e service/> (optional)
#
# Requires credentials for the registry where to push the image.
# Set in the project CI/CD settings either Docker Hub credentials:
#   DOCKER_HUB_USERNAME: Username for docker.io
#   DOCKER_HUB_PASSWORD: Password for docker.io
# or Mender Registry ones:
#   REGISTRY_MENDER_IO_USERNAME: Username for registry.mender.io
#   REGISTRY_MENDER_IO_PASSWORD: Password for registry.mender.io
#
# Passes the following variables to the build:
#   * GIT_COMMIT_TAG
#     * SHA of git commit at which build occured
#     * passed via: --build-arg GIT_COMMIT_TAG="${COMMIT_TAG}"
#

stages:
  - build
  - publish

build:docker:
  stage: build
  tags:
    - docker
  image: docker
  services:
    - docker:19.03.5-dind
  before_script:
    - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
    - export SERVICE_IMAGE=${DOCKER_REPOSITORY}:${DOCKER_TAG}
    - export COMMIT_TAG=${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  script:
    - echo "building ${CI_PROJECT_NAME} for ${SERVICE_IMAGE}"
    - docker build --build-arg GIT_COMMIT_TAG="${COMMIT_TAG}" -t $SERVICE_IMAGE ${DOCKER_DIR:-.}
    - docker save $SERVICE_IMAGE > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar

publish:image:
  stage: publish
  only:
    - /^(master|[0-9]+\.[0-9]+\.x)$/
  tags:
    - docker
  image: docker
  services:
    - docker:19.03.5-dind
  dependencies:
    - build:docker
  before_script:
    - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
    - export SERVICE_IMAGE=${DOCKER_REPOSITORY}:${DOCKER_TAG}
    - export COMMIT_TAG=${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG
    - if [ -n "$REGISTRY_MENDER_IO_USERNAME" ]; then
        echo -n $REGISTRY_MENDER_IO_PASSWORD | docker login -u $REGISTRY_MENDER_IO_USERNAME --password-stdin registry.mender.io;
      else
        echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin;
      fi
    - docker push $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker push $SERVICE_IMAGE
