# .gitlab-ci-check-docker-acceptance.yml
#
# This gitlab-ci template builds, runs and publishes into codecov acceptance
# tests from a Docker based repository.
#
# It assumes a tests/ folder with a Dockerfile for the Python test runner,
# and a Dockerfile.acceptance-testing with the recipe to build the binary
# with test coverage and serve the API.
#
# Add it to the project in hand through Gitlab's include functionality
#
# include:
#   - project: 'Northern.tech/Mender/mendertesting'
#     file: '.gitlab-ci-check-docker-acceptance.yml'
#
# Requires the following variables set in the project CI/CD settings:
# CODECOV_TOKEN: Token from codecov.io for this repository
#

stages:
  - test_prep
  - test
  - publish

test:prepare_acceptance:
  stage: test_prep
  image: docker
  services:
    - docker:19.03.5-dind
  before_script:
    - export DOCKER_REPOSITORY="mendersoftware/${CI_PROJECT_NAME}"
    - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
    - export SERVICE_IMAGE="$DOCKER_REPOSITORY:$DOCKER_TAG"
    - export COMMIT_TAG="$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA"
  script:
    - docker build -f Dockerfile.acceptance-testing -t $DOCKER_REPOSITORY:prtest .
    - docker save $DOCKER_REPOSITORY:prtest > tests_image.tar
    - docker build -t $DOCKER_REPOSITORY:pr .
    - docker run --rm --entrypoint "/bin/sh" -v $(pwd):/binary $DOCKER_REPOSITORY:pr -c "cp /usr/bin/${CI_PROJECT_NAME} /binary"
    - docker build -t testing -f tests/Dockerfile tests
    - docker save testing > acceptance_testing_image.tar
  artifacts:
    expire_in: 2w
    paths:
      - tests_image.tar
      - acceptance_testing_image.tar
      - ${CI_PROJECT_NAME}

test:acceptance_tests:
  stage: test
  tags:
    - docker
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.5-dind
  dependencies:
    - test:prepare_acceptance
  before_script:
    - apk add git bash
    - git clone --depth=1 https://github.com/mendersoftware/integration.git
    - mv integration/extra/travis-testing/* tests/
    - mv docs/* tests/
    - mv ${CI_PROJECT_NAME} tests/
    - docker load -i tests_image.tar
    - docker load -i acceptance_testing_image.tar
  script:
    - TESTS_DIR=$(pwd)/tests $(pwd)/tests/run-test-environment acceptance $(pwd)/integration $(pwd)/tests/docker-compose.yml
  artifacts:
    expire_in: 2w
    paths:
      - tests/coverage-acceptance.txt

publish:acceptance:
  stage: publish
  image: alpine
  dependencies:
    - test:acceptance_tests
  before_script:
    - apk add --no-cache bash curl findutils git
  script:
    - bash -c "bash <(curl -s https://codecov.io/bash) -Z -F acceptance -f ./tests/coverage-acceptance.txt"
